/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotemRouteImport } from './routes/totem'
import { Route as SolicitanteRouteImport } from './routes/solicitante'
import { Route as EmissaoRouteImport } from './routes/emissao'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as AtendenteRouteImport } from './routes/atendente'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TotemRoute = TotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitanteRoute = SolicitanteRouteImport.update({
  id: '/solicitante',
  path: '/solicitante',
  getParentRoute: () => rootRouteImport,
} as any)
const EmissaoRoute = EmissaoRouteImport.update({
  id: '/emissao',
  path: '/emissao',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteRoute = AtendenteRouteImport.update({
  id: '/atendente',
  path: '/atendente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendente': typeof AtendenteRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/emissao': typeof EmissaoRoute
  '/solicitante': typeof SolicitanteRoute
  '/totem': typeof TotemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendente': typeof AtendenteRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/emissao': typeof EmissaoRoute
  '/solicitante': typeof SolicitanteRoute
  '/totem': typeof TotemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendente': typeof AtendenteRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/emissao': typeof EmissaoRoute
  '/solicitante': typeof SolicitanteRoute
  '/totem': typeof TotemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/atendente'
    | '/avaliacao'
    | '/emissao'
    | '/solicitante'
    | '/totem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/atendente'
    | '/avaliacao'
    | '/emissao'
    | '/solicitante'
    | '/totem'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/atendente'
    | '/avaliacao'
    | '/emissao'
    | '/solicitante'
    | '/totem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AtendenteRoute: typeof AtendenteRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  EmissaoRoute: typeof EmissaoRoute
  SolicitanteRoute: typeof SolicitanteRoute
  TotemRoute: typeof TotemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totem': {
      id: '/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof TotemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitante': {
      id: '/solicitante'
      path: '/solicitante'
      fullPath: '/solicitante'
      preLoaderRoute: typeof SolicitanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emissao': {
      id: '/emissao'
      path: '/emissao'
      fullPath: '/emissao'
      preLoaderRoute: typeof EmissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente': {
      id: '/atendente'
      path: '/atendente'
      fullPath: '/atendente'
      preLoaderRoute: typeof AtendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AtendenteRoute: AtendenteRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  EmissaoRoute: EmissaoRoute,
  SolicitanteRoute: SolicitanteRoute,
  TotemRoute: TotemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
