/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitanteRouteImport } from './routes/solicitante'
import { Route as AtendenteRouteImport } from './routes/atendente'
import { Route as EmissaoRouteImport } from './routes/emissao'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SolicitanteRoute = SolicitanteRouteImport.update({
  id: '/solicitante',
  path: '/solicitante',
  getParentRoute: () => rootRouteImport,
} as any)

const AtendenteRoute = AtendenteRouteImport.update({
  id: '/atendente',
  path: '/atendente',
  getParentRoute: () => rootRouteImport,
} as any)

const EmissaoRoute = EmissaoRouteImport.update({
  id: '/emissao',
  path: '/emissao',
  getParentRoute: () => rootRouteImport,
} as any)

const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendente': typeof AtendenteRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/emissao': typeof EmissaoRoute
  '/solicitante': typeof SolicitanteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendente': typeof AtendenteRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/emissao': typeof EmissaoRoute
  '/solicitante': typeof SolicitanteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendente': typeof AtendenteRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/emissao': typeof EmissaoRoute
  '/solicitante': typeof SolicitanteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/atendente' | '/avaliacao' | '/emissao' | '/solicitante'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/atendente' | '/avaliacao' | '/emissao' | '/solicitante'
  id: '__root__' | '/' | '/admin' | '/atendente' | '/avaliacao' | '/emissao' | '/solicitante'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AtendenteRoute: typeof AtendenteRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  EmissaoRoute: typeof EmissaoRoute
  SolicitanteRoute: typeof SolicitanteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitante': {
      id: '/solicitante'
      path: '/solicitante'
      fullPath: '/solicitante'
      preLoaderRoute: typeof SolicitanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emissao': {
      id: '/emissao'
      path: '/emissao'
      fullPath: '/emissao'
      preLoaderRoute: typeof EmissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente': {
      id: '/atendente'
      path: '/atendente'
      fullPath: '/atendente'
      preLoaderRoute: typeof AtendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AtendenteRoute: AtendenteRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  EmissaoRoute: EmissaoRoute,
  SolicitanteRoute: SolicitanteRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
