/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitanteRouteImport } from './routes/solicitante'
import { Route as AtendenteRouteImport } from './routes/atendente'
import { Route as IndexRouteImport } from './routes/index'

const SolicitanteRoute = SolicitanteRouteImport.update({
  id: '/solicitante',
  path: '/solicitante',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteRoute = AtendenteRouteImport.update({
  id: '/atendente',
  path: '/atendente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendente': typeof AtendenteRoute
  '/solicitante': typeof SolicitanteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendente': typeof AtendenteRoute
  '/solicitante': typeof SolicitanteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendente': typeof AtendenteRoute
  '/solicitante': typeof SolicitanteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atendente' | '/solicitante'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atendente' | '/solicitante'
  id: '__root__' | '/' | '/atendente' | '/solicitante'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendenteRoute: typeof AtendenteRoute
  SolicitanteRoute: typeof SolicitanteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitante': {
      id: '/solicitante'
      path: '/solicitante'
      fullPath: '/solicitante'
      preLoaderRoute: typeof SolicitanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente': {
      id: '/atendente'
      path: '/atendente'
      fullPath: '/atendente'
      preLoaderRoute: typeof AtendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendenteRoute: AtendenteRoute,
  SolicitanteRoute: SolicitanteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
